### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment-values#1]
This is a list of stuff to go over before we launch the first public instance of Concent.

- [ ] [Django Deployment Checklist](https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/)
- [ ] [Launch Checklist for Google Cloud SQL ](https://cloud.google.com/sql/docs/postgres/launch-checklist)
- [ ] [Launch Checklist for Google Cloud Platform](https://cloud.google.com/docs/platform-launch-checklist)
- [ ] [RabbitMQ Production Checklist](https://www.rabbitmq.com/production-checklist.html)
- [ ] [Nginx Web Server Security & Hardening Guide](https://geekflare.com/nginx-webserver-security-hardening-guide/)
- [ ] Ensure that all components run versions of software with latest security fixes

The list is not complete yet. I'll be adding more later.
